name: Format, Analyze and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    # runs the CI weekly
    - cron: "0 0 * * 0"

jobs:
  default_run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: "dev"
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed -l 120 lib -l 120 example
      - run: flutter analyze lib example
      - run: flutter test --no-pub --coverage

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true